m:
	g++ main.cpp -o main
	g++ producer.cpp -o producer
	g++ consumer.cpp -o consumer
	./main

mo:
	g++ main.cpp -o main
	g++ producer.cpp -o producer
	g++ consumer.cpp -o consumer
	./main -optimize

clean:
	rm -f main producer consumer